apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: 01061875164/rabbitmq:20260430-0311-02e09cc
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
          # 1. زودنا الـ Requests عشان يقوم مستريح وميموتش من الـ OOM Killer
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1024Mi
          # 2. ظبطنا الـ Probe بأرقام منطقية وسريعة الاستجابة
          startupProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping
            initialDelaySeconds: 15  # هيستنى 15 ثانية بس ويبدأ يجرب
            periodSeconds: 10        # هيجرب كل 10 ثواني
            timeoutSeconds: 5        # لو الأمر ردش في 5 ثواني يعتبر المحاولة فشلت (بدل ما يعلق دقيقة)
            failureThreshold: 30     # هيديله 30 محاولة (يعني إجمالي 5 دقائق كاملة للـ Boot)