apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-secret
  labels:
    app.kubernetes.io/component: mysql
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: vprofile/mysql
