apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - services.yaml
  - ingress.yaml
  - deployments/apps.yaml
  - deployments/memcached.yaml
  - deployments/mysql.yaml
  - deployments/rabbitmq.yaml

labels:
  - pairs:
      app.kubernetes.io/name: vprofile
    includeSelectors: false
