apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  labels:
    app.kubernetes.io/component: vault-auth
spec:
  provider:
    vault:
      server: https://vault.el30mda.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: vprofile-dev-mysql
          serviceAccountRef:
            name: vault-mysql
